version: "3.8"
services:

  admin-server:
    image: nornickel/admin-server-image:latest
    ports:
    - "9003:9003"

  mongo:
    image: mongo
    restart: always
    env_file:
      - mongo.env
    volumes:
      - mongodb:/var/lib/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - mongo-express.env

  client-service:
    image: nornickel/client-service-image:latest
    ports:
      - "8080:8080"
    env_file:
      - client-service.env
    depends_on:
      - mongo
      - mongo-express

volumes:
  mongodb:
